### ISSUE TITLE
Modification texte et titre de la convention

### ISSUE THREAD

**Issue by juliedelauge** [cbn-alpin/sinp-paca-tickets#105]
Pour gagner en clarté et parler aux utilisateurs simplement je propose de ne pas employer le terme "géoconfidentiel(les)", mais le mot "confidentiel" tout simplement.

Remplacer le titre de la convention par : **Convention « Droit d'accès ponctuel aux données confidentielles de Silene "**
Supprimer la phrase suivante " Silene informe sur la localisation des espèces de faune et de flore et des habitats naturels ou semi-naturels". 
Les données de Silene sont librement consultables à la précision de la commune ou de la maille **(ajouter "sur Silene Nature").** 

"...a reçu lors de son inscription un identifiant et un mot de passe personnel lui permettant l’accès au portail Silene et aux données **source (supprimer "source")** des occurrences de taxons. "

**"Puisque(remplacer "puisque par " Si ")** ces droits d’accès sont accordés dans le cadre d’une étude faisant l’objet d’une ...."

**Comment by jpm-cbna** [comment]
Ok, c'est fait.

**Comment by lvahe** [comment]
On peut clore ce ticket @jpm-cbna ?

**Comment by jpm-cbna** [comment]
Oui, c'est bon.

**Comment by okristo** [comment]
Suite à l'ouverture de l'accès aux données flore, mettre à jour l'article 3 de la convention :
"Article 3. Utilisation des données Silene
Les données publiques et non sensibles relatives à la flore vasculaire et à la bryoflore sont utilisables sous licence ouverte conforme au cadre juridique du SINP : [licence ouverte (Etalab)](https://www.etalab.gouv.fr/wp-content/uploads/2017/04/ETALAB-Licence-Ouverte-v2.0.pdf).

Pour toutes les autres données, l’ouverture de droits d’accès pour Silene est strictement subordonnée au respect des conditions suivantes :"

reprendre la suite de l'article 3 tel quel.
@gkapfer est-ce que ça convient ?

**Comment by jpm-cbna** [comment]
Les corrections demandées le 7 mars sont en production.
