### ISSUE TITLE
Interrogation polygone dessiné ou importé

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-paca-tickets#11]
Sélection d’un secteur par dessin ou import de polygone : on ne peut pas interroger les données dans le polygone créé ou importé.

**Comment by jpm-cbna** [comment]
As tu essayé de cliquer sur le bouton "Rechercher" de la colonne des filtres ?

**Comment by okristo** [comment]
Non, je n'avais pas essayé! ça fonctionne en effet. Je cherchais à cliquer directement sur le polygone dessiné (la main qui apparaît lorsqu'on passe la souris sur le polygone est trompeuse). Envisageable de lancer la recherche via un clic sur le polygone?
