### ISSUE TITLE
[GeoNature] Gestion demande d'accès : colonne "Date demande" demandes en attente non renseignée

### ISSUE THREAD

**Issue by lvahe** [cbn-alpin/sinp-paca-tickets#141]
Dans l'onglet de gestion des demandes d'accès, la colonne "Date demande" de la liste des demandes en attente n'est pas renseignée.

![Capture d’écran 2021-03-12 à 11 22 53](https://user-images.githubusercontent.com/64422654/110928147-d5915700-8326-11eb-8bcd-0e0a918bec08.png)

**Comment by jpm-cbna** [comment]
Il va falloir surveiller si ce problème survient à nouveau car cela a l'air de fonctionner maintenant:

![Screenshot_20210318_213332](https://user-images.githubusercontent.com/51449363/111694017-9afd5200-8831-11eb-97b9-1e7e0f2324c4.png)

**Comment by okristo** [comment]
Le problème ne s'est pas reproduit
