### ISSUE TITLE
[GeoNature] Complément texte page d'accueil

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-paca-tickets#155]
Après le dernier paragraphe, ajouter le texte suivant : "La version actuelle de SILENE Expert correspond à une première version, elle fera l'objet d'une amélioration continue. Afin de vous orienter dans la prise en main des fonctionnalités de SILENE Expert, nous vous invitons à consulter la Foire Aux Questions."
 Ajouter le lien vers la FAQ du CMS

**Comment by okristo** [comment]
Mettre à jour le texte de la page d'accueil : 
Silene est **la plateforme régionale du SINP de Provence-Alpes-Côte d’Azur.** Silene Expert est dédié aux utilisateurs expérimentés (services de l’État, collectivités, associations, bureaux d’études, naturalistes avertis, etc.) et a pour objectif **l’accès à l’information naturaliste géolocalisée.** 

Les données mises à disposition reflètent l’état d’avancement des connaissances ou la disponibilité des inventaires et **ne peuvent être considérées comme exhaustives.** 

Pour en savoir plus sur l’organisation, les données, la façon de contribuer ou les actualités vous pouvez consulter [le site dédié à la démarche Silene ](https://silene.eu/). 

Le Conservatoire d’espaces naturels de Provence-Alpes-Côte d’Azur et les Conservatoires botaniques nationaux méditerranéen de Porquerolles et alpin, en tant que membres fondateurs de Silene accompagnent techniquement et scientifiquement le projet. 

**Sur Silene Expert, seules les données publiques non sensibles de la flore vasculaire sont accessibles à tous, sans restriction.**

Si vous souhaitez accéder aux observations géo-confidentielles restreintes (jeux de données privées avec niveau de diffusion restreint et observations sensibles), vous devez argumenter votre demande et accepter électroniquement une convention ponctuelle à l'aide du formulaire de demande de droits d'accès aux observations précises . 

(La phrase suivante doit être en gras et en rouge si possible)
Attention : Les données privées confidentielles (non libres) et les données sensibles ne sont ni rediffusables, ni réutilisables.

La version actuelle de Silene Expert fait l'objet d'une amélioration continue. Afin de vous orienter dans la prise en main des fonctionnalités de Silene Expert, nous vous invitons à consulter la rubrique « Besoin d’aide ».

**Comment by jpm-cbna** [comment]
Fait.
