### ISSUE TITLE
[GeoNature] Demande accès données précises : restreindre Zones géographiques à PACA

### ISSUE THREAD

**Issue by lvahe** [cbn-alpin/sinp-paca-tickets#163]
Lors de la procédure de demande d'accès aux données précises, il est possible de sélectionner des départements en dehors de PACA. Les utilisateurs connectés peuvent donc faire des demandes comportant des départements hors PACA : 

![bug-silene](https://user-images.githubusercontent.com/64422654/113696717-a0ccb180-96d2-11eb-8b2d-fb6c5b73a779.jpg)

Il faut restreindre la liste déroulante de "Zones géographiques" aux seuls départements de PACA.

**Comment by jpm-cbna** [comment]
Nous avons laissé la possibilité de sélectionner des communes et départements hors PACA car il y a des observations réalisées à la limite voir légèrement en dehors de la région. Du coup, ces observations sont associées à des communes et départements limitrophes hors PACA. Ce problèmes est liés à la "variabilité" des contours de communes, départements et région utilisés. Par ailleurs, certaines observations intégrées sont aussi franchement en dehors de la région ...

Lorsque nous aurons mise à jour les données flore avec le champ additionnel contenant le code commune ou département de l'observation, il sera possible de forcer l'association d'une observation à une commune en PACA même si sa géométrie l'associe à une commune ou département hors PACA.

Suite à cette opération, nous pourrons envisager la suppression des communes et départements hors PACA.
